#[derive(Debug, PartialEq, Clone)]
pub enum Token<'a> {
    Amp,
    AmpAmp,
    AmpEql,
    Bang,
    BangEql,
    Caret,
    CaretEql,
    Colon,
    Comma,
    Dash,
    DashDash,
    DashEql,
    DashGTh,
    Dot,
    Ellipsis,
    RSqu,
    Unknown(&'a str),
}